In [2]:
import time , numpy as np  ,torch 


(590106980375, 0.04506111145019531)

In [33]:
a = np.random.rand(100000000)
b = np.random.rand(100000000)

start_time_num = time.time()

# Performing multiplication
product = a * b

end_time_num = time.time()


product = 0

#start_time_for = time.time()


# Performing multiplication
#for i in range(1000000):
    #product += a[i] * b[i]

#end_time_for = time.time()

#x=  (end_time_for-start_time_for) /(end_time_num-start_time_num)
x


0.2730290598541503

In [3]:
if torch.backends.mps.is_available():
   mps_device = torch.device("mps")
   x = torch.ones(1, device=mps_device)
   print (x)
else:
   print ("MPS device not found.")

tensor([1.], device='mps:0')


In [34]:
a = torch.randint(0, 100000000, (3,), device= 'mps')
b = torch.randint(0, 100000000, (3,), device= 'mps')

start_time_mps = time.time()
torch.mps.synchronize()

c = a*b 
end_time_mps = time.time()

y=  (end_time_num-start_time_num) /(end_time_mps-start_time_mps)

y

560.6788511749347

In [4]:
x=np.array([[[1],[2]],[[3],[4]]])
x

array([[[1],
        [2]],

       [[3],
        [4]]])

In [5]:
a=np.array([[2,1],[1,3]])
np.dot(a,a)

array([[ 5,  5],
       [ 5, 10]])

In [6]:
w = np.zeros(x.shape[0],1)


TypeError: Cannot interpret '1' as a data type